title: Game website
author: Team Panda
email: team_panda@ason.ac.uk and others
description: A wonderful site to host the risk game
twitter_username: DontHaveOne
theme: jekyll-theme-cayman
plugins:
  - jemoji
